version: '3.2'
services:
  qvspot:
    container_name: qvspot
    build: ..
    restart: unless-stopped
    networks:
      - hostnet
    environment:
      ELASTICSEARCH_HOST: elasticsearch
    ports:
      - 8990:8080

networks:
  hostnet:
    external:
      name: hostnet
